// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:diamond_cart/src/home/domain/models/hive_registrar.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DiamondAdapter());
  }
}
